### ISSUE TITLE
salt and hash being set to null in MongoDB document

### ISSUE THREAD

**Issue by jmg1138** [saintedlama/passport-local-mongoose#228] opened 2017-08-25 18:12 UTC
When I tried v4.2.0 today I noticed that the salt and hash fields in the MongoDB documents were being set to null by passport.authenticate. I don't have the same behavior with v4.1.0. It looks like there were some changes in lib/authenticate.js to hide hashField & saltField by default ( [1](https://github.com/saintedlama/passport-local-mongoose/commit/a5e0ac60b933701666cca7647acfbf2d07902a62), [2](https://github.com/saintedlama/passport-local-mongoose/commit/1e1215790770635407cc277080a33daf4bc3683f) ), to avoid exposing in `req.user`, but I think those changes are setting hash and salt to null in the DB.

I cloned this repo and slightly tweaked the login example to reproduce this behavior, and it seems that having limitAttempts set to true is key to reproducing it.

**Comment by saintedlama** [comment] 2017-08-26 13:25
Fixed in 4.2.1 just released. Thanks for reporting this breaking change 👍

**Closed by saintedlama** 2017-08-26 13:25 UTC

**Comment by roblingle** [comment] 2017-09-21 13:09
The problem is that `salt` and `hash` are once again returned with users and it's added to session on `register` and `authenticate`. At least they are for me, using `email` as the username field.

Not critical at the moment for me, so I'll try to dig in later. But in general it seems like a bad-ish idea to pass those around.

**Comment by saintedlama** [comment] 2017-09-26 12:22
The problem with the fix was that `salt` and `hash` were set to `null` which may cause that the model is saved with `salt` and `hash` are set to `null` after `register` and `authenticate` which leads to a situation where users cannot login after that. I'm looking for some better way to not hand out salt and hash from the model.

**Comment by roblingle** [comment] 2017-09-26 13:30
Right. I was curious why they were set to null instead of using `delete`. Then if they were immediately saved it wouldn't overwrite those fields.

**Comment by johanquiroga** [comment] 2018-07-31 20:51
Is this suppose to be fixed ? I'm using ^5.0.1 and I think I'm having the same error, everytime I update the user via `user.save()`, the salt and hash disappear from the record and the user cannot login again
